version: '3'

volumes:
  go_cache:
  go_mod_cache:
  node_cache:

services:
  postgres-dev:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=dev
  postgres-test:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=test
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ..:/src
      - go_cache:/cache
      - go_mod_cache:/go/pkg/mod
      - node_cache:/src/node_modules
    environment:
      - DEV_DATABASE_URL="postgres://postgres:postgres@postgres-dev:5432/dev?sslmode=disable"
    depends_on:
      - postgres-dev
    ports:
      - "3000:3000"
      - "35729:35729"
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ..:/src
      - go_cache:/cache
      - go_mod_cache:/go/pkg/mod
      - node_cache:/src/node_modules
    environment:
      - TEST_DATABASE_URL="postgres://postgres:postgres@postgres-test:5432/test?sslmode=disable"
    depends_on:
      - postgres-test
